### ISSUE TITLE
type error: Argument 1 passed to Illuminate\Database\Grammar::columnize() must be of the type array, string given, called in /Applications/XAMPP/xamppfiles/htdocs/ShareMarketGame/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 131

### ISSUE THREAD

**Issue by rmit-s3562109-Adiwira-Satwika** [NickyOoi/programmingProject1#26]
All the post data seems fine. not sure what's wrong...

steps to reproduce the error:

1. click on one of the shares to buy
2. select on the trading account
3. input the amount of unit to buy
4. Click on the buy button

**Comment by s3529120** [comment]
Did you try composer dump-autoload

**Comment by rmit-s3562109-Adiwira-Satwika** [comment]
yes, still shows the same error

**Comment by rmit-s3562109-Adiwira-Satwika** [comment]
the error in the target is all i get... do u get the same error?

**Comment by s3529120** [comment]
It's being thrown from withing the framework though I need to know where in our app it came from should be on the left side of the screen when it's thrown

**Comment by rmit-s3562109-Adiwira-Satwika** [comment]
![screen shot 2018-05-05 at 6 31 14 pm 2](https://user-images.githubusercontent.com/14013276/39661299-92bbb8f4-5092-11e8-9575-e839ee8034a0.png)

**Comment by s3529120** [comment]
Scroll down in the frames section until you see one of our file names

**Comment by rmit-s3562109-Adiwira-Satwika** [comment]
![screen shot 2018-05-05 at 6 37 38 pm 2](https://user-images.githubusercontent.com/14013276/39661348-670bf60a-5093-11e8-9c7f-45f583088407.png)

**Comment by s3529120** [comment]
Program was not handling holding request well, has been reconfigured and tested and is now functional.
