### ISSUE TITLE
SQLSTATE[42S22]: Column not found

### ISSUE THREAD

**Issue by rmit-s3562109-Adiwira-Satwika** [NickyOoi/programmingProject1#31]
![screen shot 2018-05-06 at 12 58 10 pm](https://user-images.githubusercontent.com/14013276/39696232-75b2da72-5230-11e8-8120-180654a72ab2.png)

after the previous error is solved. This new error appear.

The post data is not the same as the SQL error. maybe is the error from seeder?

Steps to reproduce:

- login
- choose a stock
- complete the form and buy the stock
- error appear

**Comment by s3529120** [comment]
Please post screenshot of error location in our files rather than the framework

**Comment by rmit-s3562109-Adiwira-Satwika** [comment]
![screen shot 2018-05-07 at 8 16 17 pm](https://user-images.githubusercontent.com/14013276/39697268-b363ac90-5233-11e8-8b79-36369f8250d9.png)

**Comment by s3529120** [comment]
Laravel does not handle composite keys well, altered to use single id value (also extended this to transactions)

**Comment by s3529120** [comment]
Did you remigrate?

**Comment by rmit-s3562109-Adiwira-Satwika** [comment]
yep. issues fixed 👍🏼
