### ISSUE TITLE
Attempting to access incorrect attribute

### ISSUE THREAD

**Issue by s3529120** [NickyOoi/programmingProject1#33]
Attempting to access $list attribute in /leaderboard route which appears to be from  /home/{code}

Steps to reproduce:
    1. Login to dashboard
    2. Select "Leaderboard" from "Trading account management"

Environment encountered:
    Server: Xampp v3.2.2
    OS: WIndows v1709
    PHP v7.2.2
    Apache v2.4.29
    phpMyAdmin v4.7.7e

![screenshot-2018-5-7 whoops there was an error](https://user-images.githubusercontent.com/13671972/39698153-03b13502-5237-11e8-95db-939cecd5bcbf.png)

**Comment by rmit-s3562109-Adiwira-Satwika** [comment]
i'm sorry I have not been able to view the expected results for leaderboard. There have been many issues in other parts of the website.

**Comment by s3529120** [comment]
No worries just putting thing up as I find them just post as you have just now saying it isn't done yet and close the issue when it is completed
