### ISSUE TITLE
Issues with seeder

### ISSUE THREAD

**Issue by rmit-s3562109-Adiwira-Satwika** [NickyOoi/programmingProject1#34]
# Class TransactionTableSeeder does not exist

issues happened when trying to seed with command: 
`php artisan db:seed --class=TransactionTableSeeder`

# Cannot run the entire database seeder process

issues happened when trying to seed with command:
'php artisan db:seed'

**Exception trace:**
'ReflectionException  : Class TransactionTableSeeder does not exist

  at /Applications/XAMPP/xamppfiles/htdocs/ShareMarketGame/vendor/laravel/framework/src/Illuminate/Container/Container.php:767
    763|         if ($concrete instanceof Closure) {
    764|             return $concrete($this, $this->getLastParameterOverride());
    765|         }
    766| 
  > 767|         $reflector = new ReflectionClass($concrete);
    768| 
    769|         // If the type is not instantiable, the developer is attempting to resolve
    770|         // an abstract type such as an Interface of Abstract Class and there is
    771|         // no binding registered for the abstractions so we need to bail out.

  Exception trace:

  1   ReflectionClass::__construct("TransactionTableSeeder")
      /Applications/XAMPP/xamppfiles/htdocs/ShareMarketGame/vendor/laravel/framework/src/Illuminate/Container/Container.php:767

  2   Illuminate\Container\Container::build("TransactionTableSeeder")
      /Applications/XAMPP/xamppfiles/htdocs/ShareMarketGame/vendor/laravel/framework/src/Illuminate/Container/Container.php:646

  Please use the argument -v to see more details.
MacBook-Pro-2:ShareMarketGame Adiwira$ php artisan db:seed
Seeding: ShareCodesSeeder

   Illuminate\Database\QueryException  : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'A2M' for key 'PRIMARY' (SQL: insert into `shares` (`code`, `name`, `value`) values (A2M, The A2 Milk Company, 0))

  at /Applications/XAMPP/xamppfiles/htdocs/ShareMarketGame/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668| 

  Exception trace:

  1   PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'A2M' for key 'PRIMARY'")
      /Applications/XAMPP/xamppfiles/htdocs/ShareMarketGame/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458

  2   PDOStatement::execute()
      /Applications/XAMPP/xamppfiles/htdocs/ShareMarketGame/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458'

**Comment by s3529120** [comment]
Use only as directed in the instructions provided in the readme file and do not skip any steps previous data must be reverted in order to perform the seed
