### ISSUE TITLE
One Method of trading account creation isn't vetted

### ISSUE THREAD

**Issue by rmit-s3542282-Nick-Greenway** [NickyOoi/programmingProject1#35]
![chrome_2018-05-08_12-55-29](https://user-images.githubusercontent.com/13827765/39735637-d3692c7c-52bf-11e8-92d0-65174e1f24d3.png)
Rather self explanatory when you see the image, one method of trading account creation breaks and throws the error, this is because it is inserting the trading account into the database without vetting. 
![chrome_2018-05-08_12-56-45](https://user-images.githubusercontent.com/13827765/39735561-74da7abc-52bf-11e8-8b78-a82ff6eef679.png)

**Comment by NickyOoi** [comment]
Yeap nick, that will be the case for now, but we will be using the one on the navigation bar, Adi did told me to maintained the Trading Account Management box there, but I guess we'll remove it  once I get the permission to do so / possibly when everything is fixed.
