### ISSUE TITLE
Homepage messed up

### ISSUE THREAD

**Issue by rmit-s3542282-Nick-Greenway** [NickyOoi/programmingProject1#37]
been going through to take screenshots to put into the user doc, having this issue
![chrome_2018-05-08_21-01-24](https://user-images.githubusercontent.com/13827765/39753741-34a7ff3e-5303-11e8-89e3-ebe08ecf6f07.png)

somehow the homepage, then wants to direct to /home which doesn't exist. Not sure how to fix.

>New behaviour I was able to get around it before by navigating through already known URL's 

But just then had the same error 
![chrome_2018-05-08_21-28-40](https://user-images.githubusercontent.com/13827765/39754838-df9ceff0-5306-11e8-9564-1129e3de7b41.png)

While trying to login, this time returning to the home page and clicking this home button took me through to the dashboard.

**Comment by NickyOoi** [comment]
I have just fixed this issue, and merge the updates to master, please do give it a try Nick and do update me whether does this issue still appear? Thanks Nick.
