### ISSUE TITLE
Parse error: syntax error, unexpected '$amountheld' in SellingController.php

### ISSUE THREAD

**Issue by rmit-s3562109-Adiwira-Satwika** [NickyOoi/programmingProject1#43]
steps to reproduce:
1. Login
2. Pick a share that you have bought or buy a share
3. sell the share

![screen shot 2018-05-12 at 10 22 13 am](https://user-images.githubusercontent.com/14013276/39951848-47202756-55d1-11e8-946c-67baecdd4fa0.png)

**Comment by s3529120** [comment]
Fixed this issue new one however has arisen see #45
