### ISSUE TITLE
SOme form of request handling issue, perhaps boolean return of sell used incorrectly

### ISSUE THREAD

**Issue by s3529120** [NickyOoi/programmingProject1#45]
![screenshot_2018-05-13 whoops there was an error](https://user-images.githubusercontent.com/13671972/39964590-c48476b2-56ca-11e8-8e38-c2ff14befc09.png)

**Comment by rmit-s3562109-Adiwira-Satwika** [comment]
is it okay if you move the return to a new function so that we could implement it for front end? 

Currently, there is a function in show.blade.php to show/hide sell features.

`@unless ($stock->isEmpty())` in line 41

**Comment by rmit-s3562109-Adiwira-Satwika** [comment]
fixed by changing to a redirect action instead of return
