### ISSUE TITLE
Opening up shares 

### ISSUE THREAD

**Issue by rmit-s3542282-Nick-Greenway** [NickyOoi/programmingProject1#49]
![chrome_2018-05-20_17-27-20](https://user-images.githubusercontent.com/13827765/40276668-50664056-5c53-11e8-88b9-64da05ae6a85.png)

Trying to get the shares to open so I can get the User Doc up to date but getting this error on all stocks

E1: Seems like when I've updated I'm forgetting a php command I need to run, its happening on leaderboards also

**Comment by rmit-s3562109-Adiwira-Satwika** [comment]
have you remigrate and re seed the database?

follow the read.me file

**Comment by rmit-s3542282-Nick-Greenway** [comment]
Had done both of those, going through it again currently.

Results - ran through all the steps twice more (first time didn't work) restarted the server multiple times got it working eventually though not sure where the point of failure was. I think the rollback may have executed incorrectly for some reason.

**Comment by s3529120** [comment]
Also encountered the same issue. Followed the program flow a bit and discovered that this is due to attempting to access nickname from $list which is in this case is the share matching the given code rather than a trading account as such an access would suggest. See routes/web.php line 54-63

**Comment by rmit-s3562109-Adiwira-Satwika** [comment]
Its because not every route has $lists variable inside app2.blade. For now just change it to app.blade. @nicholas.ooi please include the list variable inside app2 so not every routes has to include list :)
