### ISSUE TITLE
Naming convention violation

### ISSUE THREAD

**Issue by s3529120** [NickyOoi/programmingProject1#52]
In the app\Http\Controllers folder there is a file named "sellController" please use camel case when naming controller files. Also if the "SellingController" is no longer required please remove it and if it is still required please use more distinct names for the 2 controllers

**Comment by NickyOoi** [comment]
In terms for that, i think its better to check with Adi, I do noticed that there are two selling controllers, but i did not removed it as I'm worried that it might affect something else, and therefore i maintained it in the file.

**Comment by rmit-s3562109-Adiwira-Satwika** [comment]
Thank you all. Duplicate controllers have been removed.
